import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CopyBtnDemo from "../components/CopyToClipboard";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>InspireFu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Hero */}
      <div className="text-7xl text-center h-screen bg-gray-200">
        <h1>Either you run the day or the day runs you</h1>
        {/* Copy to Clipboard */}
        <CopyBtnDemo />
      </div>
      {/* About */}
      {/* Experience */}
      {/* Skills */}
      {/* Projects */}
      {/* Contact */}
    </div>
  );
};

export default Home;
